---
- name : public_subnet install apache
  hosts: public_subnet
  
  become: yes
  remote_user: ec2-user
  
 
  tasks:
      - name: install apache
        yum:
           name: httpd
           state: latest
           
- name: install db in private subnet
  hosts: private_subnet
  become: yes
  remote_user: ec2-user
  
  tasks:
     - name: install java
       yum:
          name: java
          state: latest